### PR TITLE
🧹 add region to subnet name for gcp to help differentiate

### PR DESCRIPTION
**Pull request by vjeffrey**
fixes https://github.com/mondoohq/cnquery/issues/1507

### CODE REVIEW

**Comment by czunker** [comment]
That doesn't look like I would have expected:
```
cnquery run gcp project mondoo-dev-XXX -c 'gcp.compute.subnetworks{ name region.name }'
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
Query encountered errors:
1 error occurred:
	* region us-east7 not found
gcp.compute.subnetworks: [
  0: {
    region.name: "asia-east1"
    name: "default"
  }
  1: {
    region.name: "asia-east2"
    name: "default"
  }
...
```

**Comment by czunker** [comment]
Also with discoery set to `all` it looks the same:
```
cnquery run gcp project mondoo-dev-262313 --discover all -c 'gcp.compute.subnetworks{ name region.name }'              ✔ │ 14:45:30 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
! could not determine credentials for asset name=chris-calligo-dev
! could not determine credentials for asset name=debian10
! could not determine credentials for asset name=debian11
! could not determine credentials for asset name=rhel8-2
→ resolved assets resolved-assets=77
Query encountered errors:
1 error occurred:
	* region us-east7 not found
gcp.compute.subnetworks: [
  0: {
    region.name: "asia-east1"
    name: "default"
  }
  1: {
    region.name: "asia-east2"
    name: "default"
  }
...
```

**Comment by vjeffrey** [comment]
that's odd, it seems to be working for me:

Screenshot 2023-08-22 at 09 25 22
Screenshot 2023-08-22 at 09 25 33

**Comment by czunker** [comment]
Ah, ok. Thanks for the hint. Double checked the cnquery and cnspec. Both work:

image

Screenshot from 2023-08-22 19-32-06

**Review by czunker — APPROVED** [review]
LGTM. Thanks @vjeffrey

**Pull request merged**
