### PR TITLE
✨ Add container discovery to v9 os provider

### PR DESCRIPTION
**Pull request by czunker**
2nd try after https://github.com/mondoohq/cnquery/pull/1701

This fixes the issue reported in https://github.com/mondoohq/cnquery/pull/1760

### CODE REVIEW

**Comment by vjeffrey** [comment]
tried it out locally:
```
[18/09/23 09:03:45] ❯ go run apps/cnquery/cnquery.go run local --discover container -c "asset.platform"
! using builtin provider for os
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
! using builtin provider for os
asset.platform: "macos"
```

results don't seem right, but maybe it couldn't find anything and then went to the local connection as a backup? if that's true we should at least log something about it

**Comment by czunker** [comment]
> tried it out locally:
> 
> ```
> [18/09/23 09:03:45] ❯ go run apps/cnquery/cnquery.go run local --discover container -c "asset.platform"
> ! using builtin provider for os
> → loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
> ! using builtin provider for os
> asset.platform: "macos"
> ```
> 
> results don't seem right, but maybe it couldn't find anything and then went to the local connection as a backup? if that's true we should at least log something about it

Strange, I see an output:
```
cnquery run local --discover container -c "asset.platform" 
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ running container search completed container=0

```
I'm running it on my local Linux system, with docker daemon running, but no containers.

**Comment by czunker** [comment]
After a rebase, I get nearly the same output:
```
cnquery run local --discover container -c "asset.platform" --verbose                                             ✔ │ 06:40:07 
! pre-processing of cli had an error error="unknown flag: --discover"
DBG using provider os with connector local
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
DBG local> run command uname -s
DBG local> run command uname -m
DBG local> run command uname -m
DBG platform> detected os family=["debian","linux","unix","os"] platform=ubuntu
DBG local> run command hostname
DBG detected asset asset=
! using builtin provider for os
DBG detected asset asset=
DBG starting query execution qrid=qXLiKKJcpv8=
DBG finished query execution qrid=qXLiKKJcpv8=
DBG W+8HW/v60Fx0nqrVz+yTIQjImy4ki4AiqxcedooTPP3jkbCESy77ptEhq9PlrKjgLafHFn8w4vrimU4bwCi6aQ== finished
DBG graph has received all datapoints
asset.platform: "ubuntu"
```

**Comment by czunker** [comment]
It is working again as expected:
```
cnquery run local --discover container -c "asset.platform" 
! pre-processing of cli had an error error="unknown flag: --discover"
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ running container search completed container=0
```

**Review by vjeffrey — APPROVED** [review]
this is working well for me - for both the no-running-containers scenario and the running-containers scenario

**Pull request merged**
