### PR TITLE
✨ dict.flat support

### PR DESCRIPTION
**Pull request by arlimus**
... now we can flatten any parsed array structures, like: `[[1,2],3]` into `[1,2,3]`. This was not supported for `dict` structures so far, which are harder because we loose type-safety.

### CODE REVIEW

**Comment by czunker** [comment]
I tried a different test case and this resulted in a panic:
```
cnquery> [1,2,3].flat
panic: interface conversion: interface {} is []interface {}, not int64

goroutine 1 [running]:
go.mondoo.com/cnquery/llx.isTruthy({0x8a23900, 0xc0005a2cd8?}, {0xc00052642b, 0x1})
	/home/christian/workspace/mondoo/github.com/cnquery/llx/rawdata.go:189 +0x5e5
...
```
I would expect I also get `flat: any: []interface {}{1, 2, 3}` like for the other test cases.

**Comment by arlimus** [comment]
> I tried a different test case and this resulted in a panic:
> 
> ```
> cnquery> [1,2,3].flat
> panic: interface conversion: interface {} is []interface {}, not int64
> 
> goroutine 1 [running]:
> go.mondoo.com/cnquery/llx.isTruthy({0x8a23900, 0xc0005a2cd8?}, {0xc00052642b, 0x1})
> 	/home/christian/workspace/mondoo/github.com/cnquery/llx/rawdata.go:189 +0x5e5
> ...
> ```
> 
> I would expect I also get `flat: any: []interface {}{1, 2, 3}` like for the other test cases.

Thank you for catching it! Turns out this is a bug from my previous PR you found, so fixing it here.

**Comment by czunker** [comment]
Was just curious, this also works:
```
cnquery> [[1,2],3].flat.flat
flat.flat: [
  0:   any: 1
  1:   any: 2
  2:   any: 3
]
```

**Review by czunker — APPROVED** [review]
LGTM. Thanks @arlimus

**Pull request merged**
