### PR TITLE
✨ Add GCP GKE cluster network config

### PR DESCRIPTION
**Pull request by imilchev**
Add an extra property for the GCP GKE cluster network config:
```typescript
cnquery> gcp.project.gke.clusters{networkConfig{*}}
gcp.project.gke.clusters: [
  0: {
    networkConfig: {
      enableL4IlbSubsetting: false
      id: "gcp.project.gkeService.cluster/dasf432tgfre345fg/networkConfig"
      dnsConfig: {}
      serviceExternalIpsConfig: {
        enabled: false
      }
      subnetworkPath: "projects/project-1/regions/us-central1/subnetworks/mondoo-gke-cluster-2-subnet"
      privateIpv6GoogleAccess: "PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED"
      datapathProvider: "DATAPATH_PROVIDER_UNSPECIFIED"
      networkPath: "projects/project-1/global/networks/mondoo-gke-cluster-2"
      subnetwork: gcp.project.computeService.subnetwork name="mondoo-gke-cluster-2-subnet"
      enableIntraNodeVisibility: false
      defaultSnatStatus: {
        disabled: false
      }
      network: gcp.project.computeService.network name="mondoo-gke-cluster-2"
    }
  }
]
```

### CODE REVIEW

**Comment by czunker** [comment]
I wanted to try it out, but failed because of permissions:
```
failed to list clusters error="rpc error: code = PermissionDenied desc = Kubernetes Engine API has not been used in project xyz123
```

Perhaps, that's because of https://github.com/googleapis/google-cloud-go/issues/7485?

**Comment by imilchev** [comment]
> I wanted to try it out, but failed because of permissions:
> 
> ```
> failed to list clusters error="rpc error: code = PermissionDenied desc = Kubernetes Engine API has not been used in project xyz123
> ```
> 
> Perhaps, that's because of [googleapis/google-cloud-go#7485](https://github.com/googleapis/google-cloud-go/issues/7485)?
> 
> Do you know a way to work around this for now?

Yes, you can check `~/.config/gcloud/application_default_credentials.json` and manually edit it. Change the `quota_project_id` to be the project which you want to use. Then it will work

**Comment by czunker** [comment]
> > I wanted to try it out, but failed because of permissions:
> > ```
> > failed to list clusters error="rpc error: code = PermissionDenied desc = Kubernetes Engine API has not been used in project xyz123
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Perhaps, that's because of [googleapis/google-cloud-go#7485](https://github.com/googleapis/google-cloud-go/issues/7485)?
> > Do you know a way to work around this for now?
> 
> Yes, you can check `~/.config/gcloud/application_default_credentials.json` and manually edit it. Change the `quota_project_id` to be the project which you want to use. Then it will work

Thanks for the pointer. With this, I found these docs from the gcp terraform provider: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#primary-authentication

With `gcloud auth application-default login` the authentication worked. To only change the quota project via the cloud, this should also work: https://cloud.google.com/sdk/gcloud/reference/auth/application-default/set-quota-project

With all this, I tried to reproduce the issue.
- `gcloud auth application-default revoke`
- cnquery .. => `x could not find or have no access to project mondoo-edge error="google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
`
- `gcloud auth application-default login`
- cnquery ... => auth works as expected
- change the project via `gcloud config set project XYZ`. This does not change the project used by `auth application-default`
- This might lead to the above error, when the first used project for `auth application-default` does not have the needed API enabled.

**Comment by czunker** [comment]
Now, that I got the authentication working, I tried it against our edge cluster and got this error:
```
cnquery> gcp.project.gke.clusters{networkConfig{*}}
Query encountered errors:
2 errors occurred:
	* failed to create resource 'gcp.project.computeService.subnetwork': could not find resource
	* failed to create resource 'gcp.project.computeService.subnetwork': could not find resource
gcp.project.gke.clusters: [
  0: {
    networkConfig: 2 errors occurred:
	* failed to create resource 'gcp.project.computeService.subnetwork': could not find resource
	* failed to create resource 'gcp.project.computeService.subnetwork': could not find resource


  }
]
```

**Comment by czunker** [comment]
Works now also for me with and without discovery flag.

**Review by czunker — APPROVED** [review]
Thanks @imilchev

**Pull request merged**
