### PR TITLE
Disable UPX Compression

### PR DESCRIPTION
**Pull request by benr**

### CODE REVIEW

**Comment by chris-rock** [comment]
@jaym is that PR still required?

**Comment by jaym** [comment]
if its causing problems with antivirus, i don't see a problem with disabling it.

**Comment by chris-rock** [comment]
we did the upx removal in https://github.com/mondoohq/cnquery/pull/2214

**Comment by benr** [comment]
Closing this as duplicate of https://github.com/mondoohq/cnquery/pull/2214, this PR also included a skip publish capability for testing but that may cause additional problems in the future so I'll drop it for now.

**Pull request closed without merging**
