### PR TITLE
🧹 refactor github resource pack

### PR DESCRIPTION
**Pull request by chris-rock**
- restructure the code base a bit
- change the defaults for `github.repository` from `id` to `fullName`
- remove the root `github` resource that was not functional which is a left-over from pre-7 release

### CODE REVIEW

**Comment by scottford-io** [comment]
@chris-rock there is something that still doesn't feel quite right here. What I am about to say may be solved when we deliver the new `context` capabilities that @arlimus walked us through, but I feel I should call this out and get your opinion...

After connecting cnquery shell to a GitHub org (i.e. `cnquery shell github org mondoohq`), if I want to list all of the repos in that org, I have to run the query `github.organization.repositories` when it feels like I should just be able to run `github.repositories`. When I do that under this current branch I get the following:

```bash
cnquery shell github org mondoohq
→ no Mondoo configuration file provided. using defaults
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
  ___ _ __   __ _ _   _  ___ _ __ _   _
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell

cnquery> github.organization
github.organization: github.organization name="Mondoo Inc"

cnquery> github.repositories
Query encountered errors:
no user provided
```

Does this feel right to you @chris-rock?

**Comment by scottford-io** [comment]
@chris-rock I noticed that when querying an org, I can list all of the default branches like this ...

```
cnquery> github.organization.repositories { name branches.where( isDefault == true ) }
github.organization.repositories: [
  0: {
    branches.where: [
  0: github.branch name="main"
    ]
    name: "installer"
  }
  1: {
    branches.where: [
  0: github.branch name="master"
    ]
    name: "homebrew-mondoo"
  }
  2: {
    branches.where: [
  0: github.branch name="master"
    ]
    name: "ansible-mondoo"
  }
  3: {
    branches.where: [
  0: github.branch name="master"
    ]
    name: "cosmo"
  }
```

However when I connect directly to a repo and list all of the branches, the default branch is not included in the list ...

```
cnquery> github.repository.branches.where( isDefault == true )
github.repository.branches.where: []
cnquery> github.repository.branches { *}
github.repository.branches: [
  0: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="55e3111f7c91b2b6f9e8ded8158f83c6e185fd9c"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "benr/rpm-signing"
  }
  1: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="07b3dada27288fb8e6055658a57d3a7f88ad2666"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/aws-debug"
  }
  2: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="0525e54748c73272143e551a111035bf5b748ce8"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/client"
  }
  3: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="daccb7ab8ebeef4f5d4e131d6676849a516c6d35"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/gcp-bigquery"
  }
  4: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="4418fac1ada075c7113c49a10b2b4cbef38617ca"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/gcp-compute"
  }
  5: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="12ab7df99f6e98575532379b7d4a7e4ce26b4eae"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/os"
  }
  6: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="5f01970bd9cb168f486d8b60b926232c1ee81e14"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/refactor-github"
  }
  7: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="16cc20a334276b1c80b372ccf4db3aad54a43513"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/ssh"
  }
  8: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="c7d2de337df837961d97f89608d0184129e1a669"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "chris-rock/update-aws-dependencies"
  }
  9: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="48140feeda5e168c5addb43e0542eb3b5f339733"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/add_asset"
  }
  10: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="944286ec6e682c40b371fa89f4910c62ac9436f2"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/automount_sa"
  }
  11: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="732fa2bfe95117cff4797d34134144b627a06433"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/fix_auto_complete_k8s"
  }
  12: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="78115ce770d90cdfd22e0b742e925e9066940835"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/fix_empty_arg"
  }
  13: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="3c1cc40696ed6523ba64c9042a6a70982e32d550"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/fix_scan_all_namespaces"
  }
  14: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="1d65894dfbfe3dbae3adc8215b8da3ff4f468d20"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "christian/write_recorded_data"
  }
  15: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="c778bf3e23bfe4755986bde6733937f6e2919ef8"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "dependabot/go_modules/github.com/charmbracelet/bubbletea-0.23.1"
  }
  16: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="b52ea2ee573f7211af2534cf7598f1bb6b45c42f"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "dependabot/go_modules/k8s.io/apiextensions-apiserver-0.26.0"
  }
  17: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="1778a2584588614bc497624ca2d3419d2d5a9a10"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "dom/auto-expand-assessments"
  }
  18: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="624e0d90ab9d833eabb2a22b9a6f822e03f37a5f"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "dom/props-injection"
  }
  19: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="b98ac314f6ca13686577490232ed736a7088e914"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "dom/query-v2"
  }
  20: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="7895cef586a80292170dc7cd0ee183c85fcaa597"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/gcp-cloudrun-services"
  }
  21: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="12a02bf845cc9b06cc3fe6cf4b104c761ff5619a"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/gcp-compute-subnet"
  }
  22: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="1d0482c65fe4fc713dbd6b7df60c922ab4d480a1"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/gcp-dataproc-clusters"
  }
  23: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="a7737cd5db65a04575247bce971ccc96253ce955"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/gcp-sql"
  }
  24: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="34fdf85a29c6790b69eec61f3b2fc6b243d01ae2"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/k8s-check-ns"
  }
  25: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="92ae2631e8bdbb30973c7dbced40bac771c2ca63"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/move-auto-discovery"
  }
  26: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="ad8fe5921710263f660c5711c78b48a0cec43e41"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "ivan/revert-k8s-auto-discovery"
  }
  27: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="8b73f5b9ffe518056f5e323ebde0b9633eaf6222"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "jdm/choco"
  }
  28: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="348bf1ed4b7d11fb3eca90d6dfda8831c25f262e"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "jdm/mql-ctx-sketch"
  }
  29: {
    protectionRules: data is not a map to auto-expand
    isDefault: false
    repoName: "cnquery"
    protected: false
    organizationName: ""
    headCommit: github.commit sha="fac80cad6bd48c70d0b15e75a17e62ba0ef8b5da"
    owner: github.user id=99198514 name="Mondoo Inc"
    name: "jdm/msi"
  }
]
```

**Comment by scottford-io** [comment]
@chris-rock I am afraid this still isn't working as I would expect. The following query is executed against a GitHub org. I am checking all of the default branches for every repository to see if the branch is protected. The results return a bunch of repositories, but the default field is not displayed

```
cnquery> github.organization.repositories.all( branches.where( isDefault == true ).all(protected == true) )
[failed] [].all()
  actual:   [
    0: github.repository id = 191742265
    1: github.repository id = 195848173
    2: github.repository id = 257244463
    3: github.repository id = 262063902
    4: github.repository id = 262064082
    5: github.repository id = 267302742
    6: github.repository id = 290743560
    7: github.repository id = 368306299
    8: github.repository id = 395256139
    9: github.repository id = 415973920
    10: github.repository id = 431648536
    11: github.repository id = 433414105
    12: github.repository id = 453172443
    13: github.repository id = 454756854
    14: github.repository id = 465332313
    15: github.repository id = 468666119
    16: github.repository id = 473316832
    17: github.repository id = 486743172
    18: github.repository id = 487130292
    19: github.repository id = 503246692
    20: github.repository id = 506434058
    21: github.repository id = 506434989
    22: github.repository id = 514625176
    23: github.repository id = 522713459
  ]
```

If i run the query `github.organization.repositories` I do get the default field:

```
cnquery> github.organization.repositories 
github.organization.repositories: [
  0: github.repository fullName="mondoohq/installer"
  1: github.repository fullName="mondoohq/homebrew-mondoo"
  2: github.repository fullName="mondoohq/ansible-mondoo"
  3: github.repository fullName="mondoohq/cosmo"
  4: github.repository fullName="mondoohq/packer-provisioner-mondoo"
  5: github.repository fullName="mondoohq/terraform-provisioner-mondoo"
```

**Comment by chris-rock** [comment]
@scottford-io yes, this refactor removes those resources 'github.repositories' since they never worked since we released v7. When GitHub provider was experimental we also had support for users which we removed.

**Review by misterpantz — COMMENTED** [review]
descriptions are great!

**Review by vjeffrey — APPROVED** [review]
works for me locally. it's a little hard to know what resource to call, i struggled between GitHub.organization and repositories and repository, similar to what scott mentioned. but ti works. we should get some hints into the shell based on the transport used, it would be so helpful to have a couple starting commands

**Pull request merged**
