### PR TITLE
:broom: replace cockroachdb/errors with standard library errors

### PR DESCRIPTION
**Pull request by mariuskimmina**
Replacing the cockroachdb `errors.Wrap` with `errors.Join` which is available since go 1.20.

Related discussion: https://github.com/orgs/mondoohq/discussions/1328#discussioncomment-6335615

### CODE REVIEW

**Comment by mariuskimmina** [comment]
Currently seeing an error in the tests of the Terraform provider

```
--- FAIL: TestLoadHclBlocks (0.00s)
    hcl_parser_test.go:24:
                Error Trace:    /home/marius/projects/mondoo/cnquery/motor/providers/terraform/hcl_parser_test.go:24
                Error:          Not equal:
                                expected: 5
                                actual  : 4
                Test:           TestLoadHclBlocks
```

Not yet sure how it can be related to this change but the tests passes on main so it has to be.

**Comment by mariuskimmina** [comment]
This test is confusing me, here I tried a couple of different variations but only the `errors.Wrap()` seems to work (`gerrors` refers to the standard library errors in this case).
Just not returning anything there would also result in a passing test.

```
				if !d.IsDir() {
					if strings.HasSuffix(path, ".terraform/modules/modules.json") {
						modulesManifest, err = ParseTerraformModuleManifest(path)
						if errors.Is(err, os.ErrNotExist) {
							log.Debug().Str("path", path).Msg("no terraform module manifest found")
						} else {
							//return gerrors.Join(err, fmt.Errorf("could not parse terraform module manifest %s", path)) --> test fails
							//return gerrors.New(fmt.Sprintf("could not parse terraform module manifest %s", path))  --> test fails
							//return fmt.Errorf("could not parse terraform module manifest %s: %w", path, err) --> test fails
							return errors.Wrap(err, fmt.Sprintf("could not parse terraform module manifest %s", path)) // --> test passes
						}
					}
```

**Comment by tas50** [comment]
@mariuskimmina Can you rebase this PR? There's a good number of conflicts from main.

**Comment by mariuskimmina** [comment]
Hi @tas50 yea my fork was falling quite far behind, I rebased and that also fixed the weird failing test it seems

**Comment by mariuskimmina** [comment]
As this touches so many parts of the codebase it will keep getting conflicts all time if not quickly merged. I'd thus close this for now as I still try to figure out what's going on in that failing test and then try to make this change and more but smaller PRs, potentially going one package at a time.

**Comment by chris-rock** [comment]
I recommend doing this once v9 is released since we currently restructure the code quite a bit.

**Pull request closed without merging**
