### PR TITLE
🐛 gcp discovery fixes

### PR DESCRIPTION
**Pull request by imilchev**
- add `auto` and `all` discovery
- fix bigquery dataset discovery issue
- fix bigquery dataset platform ID

### CODE REVIEW

**Comment by czunker** [comment]
Discovery all is looking good:
image

Auto does not discover anything, but that's the same with v8.

Bigquery discovery is also looking good:
image

**Comment by czunker** [comment]
But something is wrong when I select a bigquery dataset:
image

Perhaps something for a follow-up PR.

**Review by czunker — APPROVED** [review]
Thanks @imilchev

**Comment by imilchev** [comment]
> But something is wrong when I select a bigquery dataset: image
> 
> Perhaps something for a follow-up PR.

aliases aren't working at the moment. If you want to query this you need to use the resource directly `gcp.project.bigqueryService.datasets{*}`

**Pull request merged**
