### PR TITLE
🧹 Add tech url segments for google workspace. Improve asset name

### LINKED ISSUE #4403: Add assetname and technology url for google workspace
**Is your feature request related to a problem? Please describe.**

Improve the default report output for Google Workspace

**Describe the solution you'd like**

- Technology URL
- Add asset name which is “primary domain + customer id”

### PR DESCRIPTION
**Pull request by preslavgerchev**
* Add tech url segments for google workspace
* Asset name now is the primary domain + the customer id. E.g. ` Google Workspace mondoo.com B1g0kA3gQ`
* Improve error message when the creds, specified in `--credentials-path` do not exist.

Fixes #4403

### CODE REVIEW

**Comment by tas50** [comment]
@preslavgerchev Where in the chart will google workspace be landing with this tech segment URL work?

**Comment by chris-rock** [comment]
@tas50 Can you provide the way you would like to have the grouping? At this point it just groups everything under Google Workspace

**Comment by tas50** [comment]
@preslavgerchev and I chatted about this. I'm going to get sign off on the proposed hierarchy before we merge this. I'll have that today.

**Comment by tas50** [comment]
@preslavgerchev Please update this to be SaaS -> Google Workspace as the categories

**Comment by preslavgerchev** [comment]
this is rfr again, the url is now saas -> google workspace (category) -> customer id

**Review by chris-rock — APPROVED** [review]
Thank you @preslavgerchev

**Pull request merged**
