### PR TITLE
⭐️ CSV export

### PR DESCRIPTION
**Pull request by chris-rock**
**Problem**

I want to export cnquery data quickly in CSV to see the data in my favorite spreadsheet app.

**Solution**

```
cnquery scan ssh chris@34.123.123.123 --output csv > report.csv
```

The response data from the query is stored in json.

You can open the report in your favorite app then:

Screenshot 2023-01-23 at 13 11 03

### CODE REVIEW

**Comment by vjeffrey** [comment]
i tried running this locally, `go run apps/cnquery/cnquery.go scan aws --output csv > report.csv`
and got:
```
→ synchronize assets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaac5d1b]

goroutine 1 [running]:
go.mondoo.com/cnquery/cli/reporter.ReportCollectionToCSV(0xc001128870, {0xd6e6380?, 0xc0009415b0})
	/Users/vj/go/src/go.mondoo.io/cnquery/cli/reporter/csv.go:46 +0x2fb
go.mondoo.com/cnquery/cli/reporter.(*Reporter).Print(0x7ff7bfeff8df?, 0xc001128870, {0xd6611e0?, 0xc000224008})
	/Users/vj/go/src/go.mondoo.io/cnquery/cli/reporter/reporter.go:71 +0x1bc
```

**Comment by czunker** [comment]
For a k8s scan, it crashes at a different point:
```
c scan k8s --querypack-bundle ../cnquery-packs/core/mondoo-kubernetes-inventory.mql.yaml -o csv > /tmp/k8s.csv                                                              
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
→ discover related assets for 1 asset(s)
→ use cluster name from kube config cluster-name=kind-kind
→ discovery option auto is used. This will detect the assets: cluster, jobs, cronjobs, pods, statefulsets, deployments, replicasets, daemonsets
→ resolved assets resolved-assets=16
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6d1a1e0]

goroutine 1 [running]:
go.mondoo.com/cnquery/explorer.(*Report).RawResults(0x0)
	/home/christian/workspace/mondoo/github.com/cnquery/explorer/report.go:9 +0x40
go.mondoo.com/cnquery/cli/reporter.ReportCollectionToCSV(0xc001c005a0, {0x9b0b1a8?, 0xc001b1e270})
	/home/christian/workspace/mondoo/github.com/cnquery/cli/reporter/csv.go:82 +0x639
go.mondoo.com/cnquery/cli/reporter.(*Reporter).Print(0x7fff13c2f1c7?, 0xc001c005a0, {0x9a86060?, 0xc000014018})
	/home/christian/workspace/mondoo/github.com/cnquery/cli/reporter/reporter.go:71 +0x1bc
go.mondoo.com/cnquery/apps/cnquery/cmd.printReports(0xc00053dc00?, 0xc00053dc00, 0x0?)
	/home/christian/workspace/mondoo/github.com/cnquery/apps/cnquery/cmd/scan.go:516 +0x11f
...
```

**Comment by chris-rock** [comment]
@vjeffrey @czunker I think I fixed the issues you brought up. Can you retest with the latest update?

**Comment by czunker** [comment]
Works for my k8s scan now. And I can import it into Google Sheets:
image

Thanks @chris-rock

**Review by czunker — COMMENTED** [review]
LGTM. Let's wait for @vjeffrey test.

**Comment by vjeffrey** [comment]
worked for my scan as well! looks good!

**Review by vjeffrey — APPROVED** [review]

**Pull request merged**
