### PR TITLE
🐛 Fix aliases for connectors

### PR DESCRIPTION
**Pull request by czunker**

### CODE REVIEW

**Review by imilchev — CHANGES_REQUESTED** [review]
This change only fixes the issue if the provider is builtin. It doesn't work if we are using an installed provider.

**Comment by czunker** [comment]
> This change only fixes the issue if the provider is builtin. It doesn't work if we are using an installed provider.

Nice catch, thanks. I fixed it with another commit:
```
cnquery run fs providers/os/connection/fs/testdata/centos8 -c "file('/etc/hostname').content" --verbose                                                                                                                    
DBG using provider os with connector filesystem
DBG no need to update provider last-refresh=38m38.131337891s provider=os
DBG running provider plugin path=/home/christian/.config/mondoo/providers/os/os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
...
file.content: "testhost"
```

**Comment by chris-rock** [comment]
I think you also need to update https://github.com/mondoohq/cnquery/blob/main/providers/defaults.go#L22

**Comment by czunker** [comment]
> I think you also need to update https://github.com/mondoohq/cnquery/blob/main/providers/defaults.go#L22

I gave that a try, and it would also work. (commit is not pushed)

But with this approach, I must add this code at two different places. And every plugin would be required to maintain its aliases in core cnquery. Is this something we would fix in a later iteration of v9?

**Review by imilchev — APPROVED** [review]
LGTM now! :shipit:

**Pull request merged**
